#!/bin/bash
# DevChain relay script — bridges Claude Code hooks to DevChain's event API.
# Auto-generated by DevChain. Do not edit manually.
# Requires: jq, curl

set -euo pipefail

# Read Claude Code hook JSON from stdin
INPUT="$(cat)"

# Bail if no API URL configured
if [ -z "${DEVCHAIN_API_URL:-}" ]; then
  exit 0
fi

# Extract hook event name from input
HOOK_EVENT_NAME="$(echo "$INPUT" | jq -r '.hook_event_name // empty')"
if [ -z "$HOOK_EVENT_NAME" ]; then
  exit 0
fi

# Capture tmux session name (fallback to env var if tmux unavailable)
TMUX_SESSION="${DEVCHAIN_TMUX_SESSION_NAME:-}"
if [ -z "$TMUX_SESSION" ] && command -v tmux >/dev/null 2>&1; then
  TMUX_SESSION="$(tmux display-message -p '#S' 2>/dev/null || true)"
fi
if [ -z "$TMUX_SESSION" ]; then
  exit 0
fi

# Build combined payload: Claude Code fields + DevChain env vars.
# Tool fields (PreToolUse/PostToolUse) are forwarded with --argjson so the
# questions OBJECT is preserved (never stringified). tool_response is size-capped
# (may be string OR object). source/tool fields are added conditionally so each
# discriminated-union variant stays strict-clean.
PAYLOAD="$(echo "$INPUT" | jq \
  --arg hookEventName "$HOOK_EVENT_NAME" \
  --arg claudeSessionId "$(echo "$INPUT" | jq -r '.session_id // empty')" \
  --arg source "$(echo "$INPUT" | jq -r '.source // empty')" \
  --arg model "$(echo "$INPUT" | jq -r '.model // empty')" \
  --arg permissionMode "$(echo "$INPUT" | jq -r '.permission_mode // empty')" \
  --arg transcriptPath "$(echo "$INPUT" | jq -r '.transcript_path // empty')" \
  --arg toolName "$(echo "$INPUT" | jq -r '.tool_name // empty')" \
  --arg toolUseId "$(echo "$INPUT" | jq -r '.tool_use_id // empty')" \
  --argjson toolInput "$(echo "$INPUT" | jq -c '.tool_input // null')" \
  --argjson toolResponse "$(echo "$INPUT" | jq -c '
    (.tool_response // null) as $r
    | if $r == null then null
      elif (($r | tostring | length) > 10000) then {truncated: true, length: ($r | tostring | length)}
      else $r end')" \
  --arg tmuxSessionName "$TMUX_SESSION" \
  --arg projectId "${DEVCHAIN_PROJECT_ID:-}" \
  --arg agentId "${DEVCHAIN_AGENT_ID:-}" \
  --arg sessionId "${DEVCHAIN_SESSION_ID:-}" \
  '{
    hookEventName: $hookEventName,
    claudeSessionId: $claudeSessionId,
    tmuxSessionName: $tmuxSessionName,
    projectId: $projectId,
    agentId: (if $agentId == "" then null else $agentId end),
    sessionId: (if $sessionId == "" then null else $sessionId end)
  }
  + (if $source != "" then {source: $source} else {} end)
  + (if $model != "" then {model: $model} else {} end)
  + (if $permissionMode != "" then {permissionMode: $permissionMode} else {} end)
  + (if $transcriptPath != "" then {transcriptPath: $transcriptPath} else {} end)
  + (if $toolName != "" then {toolName: $toolName} else {} end)
  + (if $toolInput != null then {toolInput: $toolInput} else {} end)
  + (if $toolUseId != "" then {toolUseId: $toolUseId} else {} end)
  + (if $toolResponse != null then {toolResponse: $toolResponse} else {} end)
  ')" || exit 0

# POST to DevChain API, capture response
RESPONSE="$(curl -s -f -X POST \
  -H "Content-Type: application/json" \
  -d "$PAYLOAD" \
  "${DEVCHAIN_API_URL}/api/hooks/events" \
  --max-time 10 \
  2>/dev/null)" || exit 0

# Bidirectional: output hook-compatible JSON if response contains data
if [ -n "$RESPONSE" ]; then
  # Check if response has non-empty data with additionalContext
  ADDITIONAL_CONTEXT="$(echo "$RESPONSE" | jq -r '.data.additionalContext // empty' 2>/dev/null)" || true
  if [ -n "$ADDITIONAL_CONTEXT" ]; then
    jq -n --arg ctx "$ADDITIONAL_CONTEXT" --arg evt "$HOOK_EVENT_NAME" '{
      hookSpecificOutput: {
        hookEventName: $evt,
        additionalContext: $ctx
      }
    }' 2>/dev/null || true
  fi
fi

exit 0
